// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPS
{
        public const string achievement_crazy = "CgkI0tbC_e4CEAIQBw"; // <GPGSID>
        public const string achievement = "CgkI0tbC_e4CEAIQAw"; // <GPGSID>
        public const string achievement_2 = "CgkI0tbC_e4CEAIQAg"; // <GPGSID>
        public const string achievement_3 = "CgkI0tbC_e4CEAIQBA"; // <GPGSID>
        public const string leaderboard_bestscore = "CgkI0tbC_e4CEAIQAQ"; // <GPGSID>
        public const string achievement_6 = "CgkI0tbC_e4CEAIQCA"; // <GPGSID>
        public const string achievement_4 = "CgkI0tbC_e4CEAIQBQ"; // <GPGSID>
        public const string achievement_5 = "CgkI0tbC_e4CEAIQBg"; // <GPGSID>

}

